template: php/Dockerfile.j2
images:
  php7.2-node10:
    file: Dockerfile-php7.2-node10
    base_image: php:7.2-apache-stretch
    image: itscaro/base:php7.2-node10
  php7.3-node10:
    file: Dockerfile-php7.3-node10
    base_image: php:7.3-rc-apache-stretch
    image: itscaro/base:php7.3-node10
entrypoint:
  - '"/scripts/init.sh"'
  - '"/scripts/run.sh"'

---

template: go/Dockerfile.j2
images:
  1.9:
    file: Dockerfile-1.9
    base_image: golang:1.9
    image: itscaro/go:1.9
  1.9-alpine:
    file: Dockerfile-1.9-alpine
    base_image: golang:1.9-alpine
    image: itscaro/go:1.9-alpine
  1.10:
    file: Dockerfile-1.10
    base_image: golang:1.10
    image: itscaro/go:1.10
  1.10-alpine:
    file: Dockerfile-1.10-alpine
    base_image: golang:1.10-alpine
    image: itscaro/go:1.10-alpine
